### PR TITLE
Update katharine.txt

### PR DESCRIPTION
**Pull request by jneubrand**
In this episode, katharine talks about Ye Olde Tymes™, the actual worst things, and semi-arbitrary numbers.

### CODE REVIEW

**Comment by thomasstoeckert** [comment]
Add these at line 68 before your quites to resolve issues with merging 

```
I have no recollection of that
*I should probably fix this, but ¯\_(ツ)_/¯
```

**Comment by thomasstoeckert** [comment]
And I'd suggest removing "At least thirty" - It really doesn't contribute anything to the quotes thingy

**Comment by thomasstoeckert** [comment]
Same thing with "It used to not be on the internet"
That's just dull

**Comment by jneubrand** [comment]
it used to not be on the internet is _perfect_.
Changed the rest though

**Comment by thomasstoeckert** [comment]
Didn't seem to work. Copy your quotes, update your branch, and then paste the new quotes back in

**Comment by jneubrand** [comment]
there ya go

**Comment by jneubrand** [comment]
Moving to #17; closing

**Pull request closed without merging**
